name: build
  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  jobs:
    program:
      name: build solana program
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
        - run: cargo check --workspace --exclude encrypted-ixs
    frontend:
      name: build frontend
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: '20'
            cache: yarn
        - run: yarn install --frozen-lockfile
        - working-directory: app
          run: yarn install --frozen-lockfile
        - working-directory: app
          run: yarn build
